### ISSUE TITLE
Error: invalid sender

### ISSUE THREAD

**Issue by diskigor001** [kornrunner/php-ethereum-offline-raw-tx#11]
I'm trying to send a transaction for signature, in response I get an error: Invalid sender

Example code

$nonce = '01';
        $gasPrice = '03f5476a00';
        $gasLimit = '027f4b';

        $transaction = new Web3Transaction(
            sprintf('0x%s', $nonce),
            sprintf('0x%s', $gasPrice),
            sprintf('0x%s', $gasLimit),
            '0x89ece67cad34d1c248fdd1d34a1008a3a67209bb',
            $dataUser->address,
            '1000000000000000000',
        );

        $signedTx = $transaction->getRaw($dataUser->private_key, 56);

        $web3->getEth()->sendRawTransaction(sprintf('0x%s', $signedTx), function ($err, $tx) use (&$result) {
            if ($err !== null) {
                throw new \Exception($err->getMessage());
            }

            $result = $tx;
        });

        dd($result);

**Comment by kornrunner** [comment]
It seems that you're using some different library. This repository doesn't  have `Web3Transaction` class?

**Comment by diskigor001** [comment]
use kornrunner\Ethereum\Transaction as Web3Transaction;

**Comment by diskigor001** [comment]
Duplicate of #

> It seems that you're using some different library. This repository doesn't have `Web3Transaction` class?

I just redefined the class name, since I already use class Transaction

**Comment by kornrunner** [comment]
There's no need to add hex prefix to parameters, so it should be something like:

```lang=php

   $transaction = new Web3Transaction(
        $nonce,
        $gasPrice,
        $gasLimit,
        '89ece67cad34d1c248fdd1d34a1008a3a67209bb',
        $dataUser->address,
        '1000000000000000000',
    );
```

Also `$dataUser` and it's properties are unknown, (but also shouldn't be prefixed with `0x`, assuming they're correct).
Amount should be also in hex ... not saying it's not in your example - just it looks a lot like decimal - perhaps you wanted to say `de0b6b3a7640000` instead?

Please give it a try without hex prefixes.

**Comment by diskigor001** [comment]
Thanks for the answer, I found the problem, changed the endpoint

ETH to BSC
$sweb3 = new SWeb3('https://bsc-dataseed1.binance.org:443');
