### ISSUE TITLE
Call to undefined function Mdanter error

### ISSUE THREAD

**Issue by mbsaberi** [kornrunner/php-ethereum-offline-raw-tx#3]
When I use your code and execute it after chanding with my own values, I am receiving this error:
`PHP Fatal error:  Uncaught Error: Call to undefined function Mdanter\\Ecc\\Curves\\gmp_init() in /var/www/html/vendor/mdanter/ecc/src/Curves/SecgCurve.php:122`

May you tell me pleae what is this problem for and how can I solve it? Maybe I had a mistake, or the code has a bug!

**Comment by kornrunner** [comment]
You need [`GMP`](https://www.php.net/manual/en/book.gmp.php) extension installed and enabled.
