### ISSUE TITLE
Can I use from this to create transaction in Erc20 tokens?

### ISSUE THREAD

**Issue by athamidn** [kornrunner/php-ethereum-offline-raw-tx#4]
I am currently using your package to generate transaction raw and sign it in ETH, now I want to create a transaction for tokens (ex.Tether). Can I use this package? If yes please tell us how.

**Comment by kornrunner** [comment]
Yeah, that's doable. I believe you're actually looking for https://github.com/kornrunner/php-ethereum-token#usage

Hope this helps.

**Comment by athamidn** [comment]
Great, thank you. 
$usdt  = new Token\USDT;
Can I define all other tokens? Or is it limited to what you have defined?

**Comment by kornrunner** [comment]
You can define your own token classes if package does not provide the ones you need out of the box. Just make sure they extend `kornrunner\Ethereum\Contract` and that they define decimal places and address constants, such as:

https://github.com/kornrunner/php-ethereum-token/blob/master/src/Ethereum/Token/USDT.php

**Comment by athamidn** [comment]
When I want to broadcast a trx i have created with 3 chain id for ropsten i get this error. do you know why?

"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid RLP.","data":"RlpIsTooBig"

**Comment by athamidn** [comment]
I found it why. Because you didn't write value in transaction generator inside usage section. I added it and I submitted a pull request.
