### ISSUE TITLE
Not working with chainId 56

### ISSUE THREAD

**Issue by andreitode** [kornrunner/php-ethereum-offline-raw-tx#5]
Hello,

I am trying to generate a HEX using chain ID 56, and after the sign, when I decode it, seems that uses another "sender" than the one of the private key, when generating the transaction.
By using same private key and changing only amount: from 0.1 to 0.01, changes the sender.

**Comment by kornrunner** [comment]
Thanks for reporting, it's sorted within [0.4.0](https://github.com/kornrunner/php-ethereum-offline-raw-tx/releases/tag/0.4.0)

**Comment by CrickyD** [comment]
Provided chain Id "56" must match the active chain  Id "280"
i am getting this error while testing syncswap testnet and unable to do transactions through metamask
